# Generated by Django 4.2.4 on 2023-08-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('phone', models.ImageField(upload_to='', verbose_name='телефон')),
                ('text', models.TextField(verbose_name='сообщение')),
            ],
        ),
    ]
