# Generated by Django 4.2.4 on 2023-09-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_contactdata_options_alter_contactdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='наименование'),
        ),
    ]
