# Generated by Django 4.2.4 on 2023-09-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_alter_version_versions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='versions_name',
            field=models.CharField(max_length=150, verbose_name='имя версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='versions_number',
            field=models.IntegerField(verbose_name='номер версии'),
        ),
    ]
