# Generated by Django 4.2.4 on 2023-09-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0004_alter_version_versions_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='versions_number',
            field=models.IntegerField(verbose_name='номер версии'),
        ),
    ]
